
POST http://localhost:4004/odata/v4/rims/RIMS_REQUEST
Content-Type: application/json

{
  "RequestCode": 12346,
  "typeOfRequest": "TypeB",
  "collectionLocationType": "Location2",
  "well": "WellName2",
  "wBS": "WBS002",
  "requesterLocation": "RequesterLocation1",
  "projectType": "Project2",
  "remarks": "This is a remark for the request.",
  "materials": [
    {
      "itemCode": "M003",
      "description": "Material Description 1",
      "uOM": "kg",
      "quantity": 100.000,
      "remarks_1": "Remarks for material 1"
      
    },
    {
      "itemCode": "M004",
      "description": "Material Description 2",
      "uOM": "m",
      "quantity": 200.500,
      "remarks_1": "Remarks for material 2"
    }
  ]
}

###
GET  http://localhost:4004/odata/v4/rims/RIMS_REQUEST/12346?$expand=materials


###

POST http://localhost:4004/odata/v4/rims/WELL
Content-Type: application/json


  {
      "WellCode": "AIWoP",
      "WellDescription": "AISHWAR"
  }

###

GET  http://localhost:4004/odata/v4/rims/Material

